service: f7-sls-eventbridge-lambda
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: abehera-dev
  region: ap-south-1
  stage: ${opt:stage, 'dev'}

functions:
  CreateStudent:
    handler: CreateStudent.createStudent
    events:
      - eventBridge:
          eventBus: !Ref StudentEventBus
          pattern:
            source:
              - student.create
            detail:
              type:
                - student
resources:
  Resources:
    StudentEventBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: ${self:service}-${self:provider.stage}-studentevent-bus
